//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gsutil32.rc
//
#define IDD_ABOUT                       1000
#define IDR_MAIN                        1001
#define ID_SCAN                         2000
#define ID_ABOUT                        2001
#define IDC_VERSTR                      3000
#define IDC_PORT                        3001
#define IDC_IRQ                         3002
#define IDC_BAUD                        3003
#define IDC_ID                          3004
#define IDC_IMDBUTTON                   3005
#define IDC_BUFBUTTON                   3006
#define IDC_CMDSTR                      3007
#define IDC_RSPSTR                      3008
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        1002
#define _APS_NEXT_COMMAND_VALUE         2002
#define _APS_NEXT_CONTROL_VALUE         3010
#define _APS_NEXT_SYMED_VALUE           4000
#endif
#endif
